- docs/configure/https.md
- docs/deploy.md
- docs/getstarted.md
**What type of PR is this?** documentation
This PR adds notes to the user documentation describing how to get the yaml files used in examples.
> Describe example yaml files in docs

- docs/configure/https.md
- docs/deploy.md
- docs/getstarted.md
Small fix to broken URL in docs.
> Fix url in docs

- docs/deploy.md
Updated jq command for PREFIX_LIST_ID to work on bash and zsh
```release-note
```
> minor fix to allow different shells

- docs/index.md
**What type of PR is this?** Small fix to documentation. "AWS CNI" needs to be "AWS VPC CNI" in the index.md file.
> Change AWS CNI to AWS VPC CNI

- examples/inventory-route-bluegreen-single-cluster.yaml
Bug
The blog post and single cluster blue/green HA issue
The blog post and single cluster blue/green HA issue
```release-note
```
> Changed the filename and also fixed the error

- docs/ram-sharing.md
- examples/second-account-gw1-full-setup.yaml
- examples/second-account-gw1-in-primary-account.yaml
**What type of PR is this?** test case examples
**Which issue does this PR fix**: N/A
Add yaml examples for AWS Resource Access Manager sharing ServiceNetwork (gateway) test scenario between aws accounts. AccountB do `kubectl apply -f examples/second-account-gw1-full-setup.yaml` and share created service network in  "Resource Access Manager" , then AccountA do `kubectl apply -f examples/second-account-gw1-in-primary-account.yaml`,  after that, pods in AccountA should be able to access httproute and services in AccountB
Why do we need it: It provides simple and seperate examples to test Resource Access Manager sharing ServiceNetwork …
> Add yaml examples for AWS Resource Access Manager sharing ServiceNetwork (gateway) between accounts

- controllers/gateway_controller.go
- controllers/httproute_controller.go
- examples/gateway-infra-1-namespace.yaml
- examples/inventory-route-gw-infra-1.yaml
- examples/inventory-ver1-gw-infra-1.yaml
- examples/my-hotel-gateway-infra-1-ns.yaml
- pkg/deploy/lattice/service_network_synthesizer.go
- pkg/deploy/lattice/service_network_synthesizer_test.go
- pkg/gateway/model_build_service_network_test.go
- pkg/gateway/model_build_servicenetwork.go
- pkg/model/lattice/servicenetwork.go
feature
#205 
This PR allows user to define K8S `gateway` object in non-default namespace.
The controller maps  K8S `gateway` object in non-default namespace to a VPC lattice service network which has the same name as K8S `gateway` name.
For example
```
kubectl get gaetway -A
NAMESPACE                       NAME                          CLASS
default                         my-hotel                      amazon-vpc-lattice
gw-infra-1                      my-hotel                      amazon-vpc-lattice
```
The controller will create one VPC lattice service network  called `my-hotel`
The controller will delete the VPC lattice service network `my-hotel` after K8S `my-hotel` objects …
> Support non-default namespaced gateway

- pkg/config/controller_config.go
- pkg/gateway/model_build_lattice_service.go
- pkg/gateway/model_build_servicenetwork.go
feature
VPC Lattice today only allows VPC to associate to a single ServiceNetwork.  But K8S users might desire to define multiple gateway(s) and associate HTTPRoutes to different gateway(s).  And at meantime, K8S user want Pods in the cluster(s) to access their HTTPRoute(s) might belong to different gateway(s)
We add a capability to allow user to define a CLUSTER_LOCAL_GATEWAY where this CLUSTER_LOCAL_GATEWAY is associated to current VPC.  And controller will automatically associate lattice service(HTTPRoute)  to this CLUSTER_LOCAL_GATEWAY.  
**Testing done on this …
> Add a capability that allow user to define a cluster local gateway 

- test/pkg/test/gateway.go
- test/pkg/test/httpapp.go
- test/pkg/test/path_match_httproute.go
- test/suites/integration/httproute_header_match_test.go
- test/suites/integration/httproute_path_match_test.go
feature
enhance e2e test framework to allow non-default namespaced gateway and httproute
```
Ran 2 of 2 Specs in 583.398 seconds
SUCCESS! -- 2 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestIntegration (584.30s)
PASS
ok  	github.com/aws/aws-application-networking-k8s/test/suites/integration	584.329s
``` …
> Add option to allow creating namespaced K8S resources and update path based to use non-default gateway

- controllers/eventhandlers/gateway.go
- controllers/gateway_controller.go
- controllers/service_controller.go
- pkg/config/controller_config.go
- pkg/deploy/lattice/rule_manager.go
- pkg/deploy/lattice/rule_manager_test.go
- pkg/deploy/lattice/service_network_synthesizer_test.go
- pkg/deploy/lattice/target_group_manager.go
- pkg/deploy/lattice/target_group_synthesizer.go
- pkg/deploy/lattice/target_group_synthesizer_test.go
- pkg/deploy/lattice/targets_manager.go
- pkg/deploy/lattice/targets_manager_test.go
- pkg/deploy/lattice/targets_synthesizer.go
- pkg/deploy/lattice/targets_synthesizer_test.go
- pkg/deploy/stack_deployer.go
- pkg/gateway/model_build_listener_test.go
- pkg/gateway/model_build_rule.go
- pkg/gateway/model_build_servicenetwork.go
- pkg/gateway/model_build_targetgroup.go
- pkg/gateway/model_build_targetgroup_test.go
- pkg/gateway/model_build_targets.go
- pkg/gateway/model_build_targets_test.go
- pkg/latticestore/latticestore.go
- pkg/latticestore/latticestore_test.go
- pkg/model/lattice/rule.go
- pkg/model/lattice/targets.go
- pkg/runtime/reconcile.go
cleanup and feature
#98 
#9
* refactor internal cache(datastore) for target group 
**  update key for target group to  <k8s service name, k8s service namespace, HTTProute name>  
**   for serviceexport and serviceimport,  the HTTPRoute name is null
* introduce a mode `TARGET_GROUP_NAME_LEN_MODE`
** if `TARGET_GROUP_NAME_LEN_MODE` == "long"
The target group name is k8s-(K8S-service-name)-(k8s-service-namespace)-(HTTPRoutename)-(VPCid)
** otherwise
The target group name is k8s-(k8s-service-name)-(k8s-service-namespace)
```
make presubmit. …
```
> Add capability to allow lattice target group name include current vpc and httproute 

- docs/conformance-test.md
documentation
#9 
This is a test report using code from  https://github.com/aws/aws-application-networking-k8s/pull/230 and latest gateway api conformance test
```release-note
```
> Add gateway api conformance test report

- controllers/httproute_controller.go
bug
This will make httproutes to be properly recognized as "accepted", in external integrations such as ExternalDNS.
This is required if we go ExternalDNS integration path, and will also help later as we support more addons.
In a manual test setting on `kubectl get httproute byoc-parking -o yaml`:
```yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
annotations:
application-networking.k8s.aws/lattice-assigned-domain-name: byoc-parking-default-04dbcef00d405a0fd.7d67968.vpc-lattice-svcs.us-west-2.on.aws …
```
> Fix HTTPRoute status to match API standard

- pkg/gateway/model_build_targetgroup.go
- test/suites/integration/httproute_path_match_test.go
- test/suites/integration/https_listener_weighted_rule_with_service_export_import_test.go
bugfix
Addresses #86. Currently named targetPorts cause error because it triggers CreateTargetGroup request with port 0. With this PR it will trigger request with port 80 instead.
1. TargetPort actually does not matter at all. To understand this we need to understand how ports are working in Lattice TGs. Ports defined in Lattice TGs only acts as a "default port" when no port is specified in RegisterTargets API. Since we always populate port when creating targets, the port on TG does nothing. We do not need an accurate number on this field.
2. But can't we still query the endpoint and find the port name? This path seems complicated. For example, there could be multiple pods using …
> Fix TG creation when using named targetPorts

- controllers/eventhandlers/endpoints.go
- controllers/eventhandlers/service.go
- controllers/service_controller.go
- pkg/gateway/model_build_targets.go
- pkg/gateway/model_build_targets_test.go
bug
https://github.com/aws/aws-application-networking-k8s/issues/237
Fix
make e2etest
Manually run https://github.com/aws/aws-application-networking-k8s/issues/257
No
No
No
```release-note
```
> Fix service delete event

- controllers/eventhandlers/gateway.go
- controllers/eventhandlers/service.go
- controllers/eventhandlers/serviceimport.go
- controllers/gateway_controller.go
- controllers/httproute_controller.go
bug/feature
Add GatewayAddress to status, and fix some bugs related to namespace on controller.
* `make e2etest`
* GW conformance test (in the existing way)
Now when we create gateway and add HTTPRoutes successfully, the gateway will look like (for example):
```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
annotations:
application-networking.k8s.aws/lattice-vpc-association: "true"
creationTimestamp: "2023-06-01T17:04:36Z"
finalizers:
- gateway.k8s.aws/resources
generation: 1
labels:
testing.kubernetes.io: "true" …
```
> Fix gateway status update and add address

- test/pkg/test/framework.go
As we recently changed the method to read Config file in 
https://github.com/aws/aws-application-networking-k8s/pull/264
We need to explicitly do config.ConfigInit() when create the test framework
- Did the 	fmt.Println("config.Region: ", config.Region), it could read the correct `config.Region`
- `make e2etest` all can pass
```
• [253.448 seconds]
Ran 3 of 3 Specs in 769.177 seconds
SUCCESS! -- 3 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestIntegration (769.41s)
PASS
ok  	github.com/aws/aws-application-networking-k8s/test/suites/integration	770.031s
```
> Init Config for test framework

- Makefile
- pkg/deploy/lattice/target_group_manager.go
- pkg/deploy/lattice/target_group_manager_test.go
- pkg/deploy/lattice/target_group_synthesizer.go
- pkg/deploy/lattice/target_group_synthesizer_test.go
- pkg/deploy/stack_deployer.go
- pkg/gateway/model_build_lattice_service.go
- pkg/gateway/model_build_targetgroup.go
- pkg/gateway/model_build_targetgroup_test.go
- test/pkg/test/framework.go
- test/suites/integration/httproute_header_match_test.go
- test/suites/integration/httproute_mutation_do_not_leak_target_group_test.go
Trying to solve this Target Groups Leaked  issue: https://github.com/aws/aws-application-networking-k8s/issues/119
Modified version of this PR: https://github.com/aws/aws-application-networking-k8s/pull/268
- Changed model_build_targetgroup and model_build_service, make sure target group deletion request `model` triggered by httproute deletion could pass to target_group_synthesizer correctly
- Changed lattice resource creation and deletion order for httproute. Before both creation and deletion follow the same order: first TargetGroup then LatticeService. Now, the creation order keep the first TargetGroup then LatticeService, while the the deletion order change to first  LatticeService then TargetGroup
- The reason to do this change is vpc lattice don't support to delete a still-in-use …
> Fix Httproute deletion  leaking Target Group issue

- controllers/gateway_controller.go
- controllers/httproute_controller.go
- docs/conformance-test.md
- pkg/deploy/lattice/listener_manager.go
- pkg/deploy/lattice/service_manager.go
- pkg/deploy/lattice/service_manager_test.go
- pkg/latticestore/latticestore.go
- pkg/utils/common.go
- test/pkg/test/framework.go
- test/pkg/test/header_match_httproute.go
- test/pkg/test/path_match_httproute.go
- test/pkg/test/weighted_routing_httproute.go
- test/suites/integration/httproute_header_match_test.go
- test/suites/integration/httproute_path_match_test.go
- test/suites/integration/https_listener_weighted_rule_with_service_export_import_test.go
bug
* #260 - TG and service long names are not what we intended, fixing to a correct name
* Setting route status, only support plain Accepted status, other statuses should be covered by #277 
* Do not attach route to gateway if port does not match
Fixes multiple bugs for testing
```
make e2etest
```
Conformance test results also updated.
**Does this PR introduce any …
> Update resource naming and conformance

- pkg/deploy/stack_deployer.go
- pkg/deploy/stack_deployer_test.go
- test/suites/integration/deregister_targets_test.go
bug
- Add unit tests for `stack_deployer.go`
- Fix e2e test build failure
This PR add unit tests for `stack_deployer.go` and fix e2e test build failure
#274 
`make e2etest`
```
• [271.541 seconds]
Ran 6 of 6 Specs in 2329.978 seconds
SUCCESS! -- 6 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestIntegration (2330.79s)
PASS
ok      github.com/aws/aws-application-networking-k8s/test/suites/integration   2330.817s
```
N/A
No …
> test: add unit tests for `stack_deployer.go`

- examples/elasticsearch-export.yaml
- examples/elasticsearch-import.yaml
- examples/elasticsearch.yaml
- pkg/gateway/model_build_targets.go
- pkg/gateway/model_build_targets_test.go
- test/pkg/test/elasticsearch.go
- test/pkg/test/service_export_import.go
- test/suites/integration/srvexport_port_annotation_targets_test.go
**What type of PR is this?** Feature
**Which issue does this PR fix**: AWS#267
**What does this PR do / Why do we need it**: This PR enables users to define which port/container to be exported vi ServiceExport object.
**Testing done on this change**: Yes
make presubmit output:
```go
?       github.com/aws/aws-application-networking-k8s/pkg/aws   [no test files]
?       github.com/aws/aws-application-networking-k8s/pkg/deploy        [no test files]
ok      github.com/aws/aws-application-networking-k8s/pkg/aws/services  0.017s  coverage: 2.9% of statements
ok      github.com/aws/aws-application-networking-k8s/pkg/config        0.011s  coverage: 77.4% of statements
? …
```
> AWS#267 Added support for Port Annotation in ServiceExport Object

- docs/deploy.md
- examples/deploy-v0.0.13.yaml
- helm/Chart.yaml
- helm/values.yaml
**Which issue does this PR fix**: Release version v0.0.13
**What does this PR do / Why do we need it**: Release version v0.0.13
Published the v0.0.13  image https://gallery.ecr.aws/aws-application-networking-k8s/aws-gateway-controller
Did:
helm install gateway-api-controller   --version=v0.0.13 
and then `make e2etest` could all pass
```
Ran 7 of 7 Specs in 2910.970 seconds
SUCCESS! -- 7 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestIntegration (2911.29s)
```
**Will this break upgrades or downgrades. Has updating a running …
> Release version v0.0.13

- controllers/conditions.go
- controllers/gateway_controller.go
- controllers/httproute_controller.go
bug
Follow-up to a fix of #282 - also partially fixes #277 
Total rework of conditions update - now conditions are handled individually, and got rid of infinite loop and missing updates
```release-note
```
> Fix condition handling of gateways and routes

- controllers/httproute_controller.go
Improves troubleshooting when HTTPRoute is pointing to wrong namespace for its gateway parent.
documentation
https://github.com/aws/aws-application-networking-k8s/issues/285
Improves logging
Tested on running cluster
N/a
No
Yes
No
By submitting this pull request, I confirm that my contribution is made under the terms of …
> Use log level 2 when controller can not find Parent Gateway for HTTPRoute

- docs/getstarted.md
This CR fixes a small syntax error in the latest getting started docs.
documentation
N/a
Fixes syntax error when running getting started docs. When running the docs in ZSH or running them a second time there could be additional httpRoute entries and we need to specify the first one.
Running through getting started with a clean environment
N/a
No
testing in running cluster
No
By submitting this pull request, I confirm that my …
> Fix small issue with getting started doc

- test/suites/integration/https_listener_weighted_rule_with_service_export_import_test.go
**Which issue does this PR fix**: bug
**What does this PR do / Why do we need it**:  this PR fix clean up issue for test `Test 2 listeners gateway with weighted httproute rules and service export import`
**If an issue # is not available please add repro steps and logs from aws-gateway-controller showing the issue**: N/A
`make e2etest` output:
```
Ran 7 of 7 Specs in 2926.795 seconds
SUCCESS! -- 7 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestIntegration (2927.51s)
PASS
ok      github.com/aws/aws-application-networking-k8s/test/suites/integration   2927.541s
```
**Automation added to e2e**: N/A
**Will this break upgrades or downgrades. Has updating a running cluster …
> fix: clean up resources after test run

- .gitignore
- docs/developer.md
> update e2etest instructions; update gitignore for local files

- .gitignore
This pull request adds .idea/ to the .gitignore file. This change ensures that JetBrains IDE settings and configurations are not tracked by Git.
By ignoring the .idea/ directory (used by JetBrains IDEs like IntelliJ IDEA, PyCharm, WebStorm, etc.), we allow each developer to have their own local settings without interfering with the project's source code.
This change is purely related to the project's development environment and has no impact on the actual codebase or functionality.
> Added .idea/ to .gitignore

- Makefile
- test/suites/integration/httproute_creation_test.go
- test/suites/integration/httproute_update_test.go
Feature, additional HTTPRoute E2E Tests
#273
Adds HTTPRoute creation/update E2E tests to improve test coverage
```
FOCUS="" make e2etest
...
Ran 11 of 11 Specs in 4656.643 seconds
SUCCESS! -- 11 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestIntegration (4656.81s)
PASS
```
N/A
No.
This will not break upgrades or downgrades. These changes were tested on the latest v0.0.15 release.
No, only …
> Added HTTPRoute Creation/Update E2E Tests

- controllers/gateway_controller.go
- controllers/httproute_controller.go
- pkg/gateway/model_build_lattice_service.go
- pkg/gateway/model_build_lattice_service_test.go
- pkg/gateway/model_build_listener.go
- pkg/gateway/model_build_listener_test.go
- pkg/gateway/model_build_rule.go
- pkg/gateway/model_build_rule_test.go
- pkg/gateway/model_build_targetgroup.go
- pkg/gateway/model_build_targetgroup_test.go
- pkg/k8s/utils.go
- pkg/model/core/route.go
- test/pkg/test/framework.go
cleanup
This is a preliminary step for #25 
The primary goal of this PR is to abstract away Gateway API's route constructs. There are no functionality changes made here.
Currently, HTTPRoute is available in the v1beta1 package, but GRPCRoute is only available in v1alpha2. Due to their different types and packages, they have no common parent. Additionally, changes are expected in the future, as these are experimental packages. Putting all Gateway API Route constructs behind an abstraction gives us more control over how the rest of our code interacts with them and reduces the amount of refactoring needed in the future. In the case of #25 , we need to support multiple types of routes …
> Abstract Routes to Support Multiple Route Types

- pkg/config/controller_config.go
- pkg/config/controller_config_test.go
The code under test falls back to reading AWS region, account ID, and VPC ID from Instance Metadata Service. The tests currently assume that this service is unavailable. This means they fail when run in environments where this service is available to tests.
This commit fixes this issue by making the tests use a mock Instance Metadata Service which returns an error. This ensures that these tests work as expected regardless of whether Instance Metadata Service is available/reachable.
Fixes broken tests
pkg/config/controller_config_test.go fails in environments with access to AWS EC2 Instance Metadata Service.
Unbreaks tests in environments with IMDS accessible.
**Testing done on this …
> Make IMDS unavailable in controller config tests (#336)

- test/pkg/test/framework.go
- test/suites/integration/deregister_targets_test.go
- test/suites/integration/httproute_creation_test.go
- test/suites/integration/httproute_header_match_test.go
- test/suites/integration/httproute_method_match_test.go
- test/suites/integration/httproute_mutation_do_not_leak_target_group_test.go
- test/suites/integration/httproute_path_match_test.go
- test/suites/integration/httproute_update_test.go
- test/suites/integration/https_listener_weighted_rule_with_service_export_import_test.go
- test/suites/integration/srvexport_port_annotation_targets_test.go
E2E test code improvement
- Add two helper functions in the test framework IsVpcAssociateWithServiceNetwork() and IsAllLatticeTargetsHealthy()
- Get rid of above 3min fixed wait time, instead, use above helper functions and Eventually() block to make use vpc lattice connectivity setup is fully ready
- Fix bug in the deregister_targets_test.go test cases
**What does this PR do / Why do we need it**: E2E test code improvement
No
**Will this break upgrades or downgrades. Has updating a running cluster been tested?**: No
**Does this PR introduce any user-facing …
> E2E test improvement, get rid of fixed wait time, trying to avoid lattice targets draining,fixing deregister_targets_test

- test/pkg/test/framework.go
- test/pkg/test/header_match_httproute.go
- test/pkg/test/service_export_import.go
- test/pkg/test/weighted_routing_httproute.go
- test/suites/integration/deregister_targets_test.go
- test/suites/integration/httproute_creation_test.go
- test/suites/integration/httproute_header_match_test.go
- test/suites/integration/httproute_method_match_test.go
- test/suites/integration/httproute_mutation_do_not_leak_target_group_test.go
- test/suites/integration/httproute_path_match_test.go
- test/suites/integration/httproute_update_test.go
- test/suites/integration/https_listener_weighted_rule_with_service_export_import_test.go
- test/suites/integration/srvexport_port_annotation_targets_test.go
- test/suites/integration/suite_test.go
cleanup
n/a
Improves dev quality of life, following on from https://github.com/aws/aws-application-networking-k8s/pull/330, this PR further improves the performance of e2e tests, their reliability, and resource cleanup. Main features of this PR:
* Provision a single gateway for the test suite
* Create all objects against the "non-default" namespace
* Move all persistent objects out of individual tests to allow cleanup even on failure
* Update all ```Eventually()``` blocks to use local expectations so failed assertions do not break out
* reliability enhancements
* minor refactoring
e2e tests
```
Ran 11 of 11 Specs in 1744.934 seconds
SUCCESS! -- 11 …
```
> e2e test enhancements for better performance and reliability

- test/suites/integration/defined_target_ports_test.go
This PR change the way to clean up e2e test and seems it break the `defined_target_ports_test.go `, we should change this test file accordingly.  https://github.com/aws/aws-application-networking-k8s/pull/344
`make e2etest` success for `defined_target_ports_test.go` :
Ran 3 of 13 Specs in 741.309 seconds
SUCCESS! -- 3 Passed | 0 Failed | 0 Pending | 10 Skipped
PASS | FOCUSED
> Fix resource clean up for defined_target_ports_test.go

- controllers/gateway_controller.go
- controllers/route_controller.go
- controllers/serviceexport_controller.go
- docs/getstarted.md
- examples/ipv6-cluster.yaml
- pkg/deploy/lattice/target_group_manager.go
- pkg/deploy/lattice/target_group_synthesizer_test.go
- pkg/gateway/model_build_targetgroup.go
- pkg/gateway/model_build_targetgroup_test.go
- pkg/model/core/route.go
- pkg/model/lattice/targetgroup.go
- pkg/utils/condition.go
feature
#168 
This PR adds IPv6 support for Service
`make e2etest` ran in an IPv6 clustere outputs:
```
Ran 11 of 11 Specs in 4135.156 seconds
SUCCESS! -- 11 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestIntegration (4135.90s)
PASS
ok      github.com/aws/aws-application-networking-k8s/test/suites/integration   4135.930s
```
**Automation added to e2e**: N/A. All existing e2e tests can be run a IPv6 cluster
**Will this break upgrades or downgrades. Has updating a running …
> feat: add IPv6 target group support

- pkg/gateway/model_build_targetgroup.go
- pkg/gateway/model_build_targets.go
- pkg/gateway/model_build_targets_test.go
- test/pkg/test/nginxapp.go
- test/suites/integration/defined_target_ports_test.go
bug
#241 
Interpret backendRef port "correctly", it should be service port, not target port per [gwapi documentation](https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1beta1.BackendObjectReference).
To do this, we need to figure out what is the right set of endpoint ports only based on the service port. We can deduce this by the following logic:
* [A service port MUST have a name if there are multiple ports exposed from a service](https://kubernetes.io/docs/concepts/services-networking/service/#multi-port-services). Therefore, if a port is named, endpoint port is only relevant if it has the same name.
* If a service port is unnamed, it MUST be the only …
> Use right port on backendRef port match

- test/pkg/test/framework.go
- test/pkg/test/grpc_helloworld.go
- test/pkg/test/grpcbin.go
- test/pkg/test/grpcurl_runner.go
- test/suites/integration/defined_target_ports_test.go
- test/suites/integration/grpcroute_traffic_test.go
- test/suites/integration/suite_test.go
**Which issue does this PR fix**: feature
- Add grpcurl as a grpc client pod
- Add helper function `RunGrpcurlCmd()` to send grpc request
- Add grpc server grpcbin.go and grpc_helloworld.go
Newly added test case can pass
```
Ran 1 of 14 Specs in 102.793 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 13 Skipped
PASS | FOCUSED
```
All e2e test can pass
```
Ran 14 of 14 Specs in 1993.337 seconds
SUCCESS! -- 14 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestIntegration (1993.66s)
PASS
```
**Will this PR introduce any new …
> Add GRPC e2etest helper functions

- cmd/aws-application-networking-k8s/main.go
- pkg/aws/cloud.go
- pkg/aws/cloud_mocks.go
- pkg/aws/cloud_test.go
- pkg/config/controller_config.go
- pkg/config/controller_config_test.go
- pkg/deploy/lattice/service_manager.go
- pkg/deploy/lattice/service_manager_test.go
- add ClusterName property to config
- create generic tag for resources that gateway should manage
- add helper methods for tags
- remove EKS sdk client, it's not used
- update logic for service_manager when we create and update service
- when create, add default tags to association
- when update, check managedBy tag before deleting association
- update #317 
- update #342  
- update #310 
- updated unit tests with tags validation
- manually tested `getClusterName` using metadata with deploying k8s pod (my cluster name is "cl")
```bash
kubectl run -it gateway --image {accountid-redacted}.dkr.ecr.us-west-2.amazonaws.com/cl-repo:gateway
{"level":"info","ts":1692932391.0858064,"logger":"setup","caller":"workspace/main.go:106","msg":"init …
```
> add generic managedBy tag, fix deletion for not managed Sn-Service associations

- config/crds/bases/application-networking.k8s.aws_targetgrouppolicies.yaml
- examples/target-group-policy.yaml
- helm/crds/application-networking.k8s.aws_targetgrouppolicies.yaml
- pkg/apis/applicationnetworking/v1alpha1/targetgrouppolicy_types.go
- pkg/apis/applicationnetworking/v1alpha1/zz_generated.deepcopy.go
- pkg/deploy/lattice/target_group_manager.go
- pkg/deploy/lattice/target_group_manager_test.go
- pkg/deploy/lattice/target_group_synthesizer.go
- pkg/deploy/lattice/target_group_synthesizer_test.go
- pkg/gateway/model_build_targetgroup.go
- pkg/gateway/model_build_targetgroup_test.go
- pkg/latticestore/latticestore.go
- pkg/model/lattice/targetgroup.go
- test/pkg/test/framework.go
- test/suites/integration/httproute_mutation_do_not_leak_target_group_test.go
- test/suites/integration/httproute_update_test.go
feature
#304 #315 (partial) #69 
Now supporting configuring target group protocols and health checks by attaching TargetGroupPolicy CRD to k8s Service.
This PR includes breaking change on Lattice target group naming scheme. Now TG names on VPC Lattice include protocol and protocol version - this is necessary for avoiding conflicts and supporting a few service export scenarios.
I also have increased the name size to allow longer names.
Whenever a TargetGroupPolicy is applied for existing target group, if protocol / protocolVersion is changed:
* New target group will be created by TG synthesizer, since now the TG name is different.
* Once new target group is active, it will be picked …
> Update target group info using TargetGroupPolicy

- docs/configure/https.md
- docs/developer.md
- docs/reference/target-group-policy.md
documentation
```release-note
```
> Add TargetGroupPolicy docs

- pkg/aws/cloud.go
- pkg/aws/cloud_test.go
`lattice.ListTagsForResource(tagsReq)` can return NotFound error when I search association tags.
Error observed when association was created in different account. Use case
**Service A** exists in **account A**. Service **A** shared with _account  B_. _Account B_ creates association with _SN in B_ with **service A**. 
So Association belongs to account B, but service is managed by controller in account A.
For some reason ListTagsForResource does not return Lattice ResourceNotFoundException, but generic not found. Following error handling **is not working**
```go
if aerr, ok := err.(awserr.Error); ok {
if aerr.Code() == vpclattice.ErrCodeResourceNotFoundException {
err = nil
}
}
```
> ignore errors when get tags for service - Sn association

- pkg/deploy/externaldns/dnsendpoint_manager.go
- pkg/gateway/model_build_lattice_service.go
- pkg/gateway/model_build_lattice_service_test.go
- pkg/model/lattice/service.go
bug
Sets correct owner reference for DNSEndpoint if parent is GRPCRoute.
Prevents leaking DNSEndpoint resource.
```release-note
```
> Fix DNSEndpoint owner reference for GRPCRoute

- config/iam/recommended-inline-policy.json
- docs/deploy.md
- examples/recommended-inline-policy.json
We recently change `getClusterName()` it will invoke `ec2Client.DescribeTags(tagReq)` to get the cluster name, so that the controller's iamserviceaccount should have this permission as well, otherwise it has this error:
```
{“level”:“fatal”,“ts”:1693435021.1204855,“logger”:“setup”,“caller”:“workspace/main.go:104”,“msg”:“init config failed: cannot get cluster name: UnauthorizedOperation: You are not authorized to perform this operation.\n\tstatus code: 403, request id: dbe973a6-ea26-4548-add4-9d4e2d3772ab”,“stacktrace”:“main.main\n\t/workspace/main.go:104\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250”}
``` 
https://github.com/aws/aws-application-networking-k8s/blob/3fdd1c954162eef02bea4b0261b0ab334a9a4f53/pkg/config/controller_config.go#L125C27-L125C39
Add this permision and run …
> Add `ec2:DescribeTags` permission in VPCLatticeControllerIAMPolicy

- docs/configure/environment.md
- docs/reference/target-group-policy.md
- mkdocs.yml
documentation
* Updates TargetGroupPolicy reference to mention restrictions on gRPC health checks.
* Also restructured doc a bit, now includes environment setting in the website
```release-note
```
> Update docs with latest guide on health checks

- controllers/service_controller.go
- test/suites/integration/deregister_targets_test.go
…8sService deletion
**Which issue does this PR fix**: bug fix for #331
It's quite possible that this previous refactoring [service_controller.go](https://github.com/aws/aws-application-networking-k8s/pull/360/files#diff-00e81e75f6d3a8e448c8698e8838e914e508f7bb66e569da6fdd3d394baf96e5), cause a regression that "deleting k8sService do NOT de-registering targets".  Bring back the  `(r *serviceReconciler) reconcileTargetsResource()` logic to handle the k8sService deletion could fix this issue 
**What does this PR do / Why do we need it**: bug fix for #331
newly un-commented e2etest case …
> [Bug fix] Revive serviceReconciler.reconcileTargetsResource() to handle k8sService deletion de-registering targets

- docs/developer.md
Note:
Go v1.21 is out and there are problems with unit tests. Stating explicit version in docs.
> update go version in docs

- pkg/deploy/lattice/target_group_synthesizer_test.go
- pkg/gateway/model_build_targetgroup.go
- pkg/gateway/model_build_targetgroup_test.go
- test/pkg/test/framework.go
- test/suites/integration/serviceexport_mutation_test.go
**Which issue does this PR fix**:  Partial bug fix for #269
This is the **Partial** bug fix for serviceexport deletion leaking targetgroup issue, just fixed serviceexport's serviceImport not being referenced by Route scenario. _To fix the serviceImport being referenced by Route scenario, it need to change dataStore in many various places, That change is hard to trace and review, we need to do it in a separate PR, or do the dataStore refactoring first._ 
-  Used `inventory-ver2.yaml `  and`inventory-ver2-export.yaml` did the  different order k8s resource creation/deletion  manual tests. Traced all related code path by single-step debugger, it works as expected
- Added new e2etest cases, new test cases and whole test suite can pass
```
Ran 31 of 31 Specs in …
```
> Partial bug fix for serviceexport deletion leaking targetgroup issue

- Makefile
- docs/developer.md
- test/pkg/test/grpcurl_runner.go
- test/pkg/test/metadata.go
- test/suites/integration/suite_test.go
Note:
- Change e2e tests namespace from "non-default" to "e2e-test"
- Create e2e-test namespace if does not exists in Makefile
- Add cleanup script in Makefile. Namespace deletion and creation is an ultimate cleaner, no need to track resources individually.
Tested with running, terminating, cleaning, and running again e2e-tests.
Closes #293
Closes #231
> add e2e cleanup script

- .gitignore
- cmd/aws-application-networking-k8s/main.go
- controllers/eventhandlers/mapper.go
- controllers/eventhandlers/mapper_test.go
- controllers/eventhandlers/vpcAssociationPolicy.go
- controllers/gateway_controller.go
- examples/vpc-association-policy.yaml
- Add a helper `resourceMapper.policyToTargetRefObj()` so that both VpcAssociationPolicyToGateway() and TargetGroupPolicyToService could leverage it
- Mimic #360, Add the `vpcAssociationPolicyEventHandler.MapToGateway()` method
- Make gateway_controller optionally watches the `VpcAssociationPolicy`
**What type of PR is this?**  Prepare for SNVA Security Group Api support #199 
**What does this PR do / Why do we need it**: Prepare for SNVA Security Group Api support
- More unit test for `mapper.go` 
- Manual test done: `kubectl apply -f examples/vpc-association-policy.yaml` could enter the `gatewayReconciler.Reconcile()` method if targetRef gateway exists
- E2E test all pass
```
Ran 31 of 31 Specs in 2006.710 seconds
SUCCESS! -- 31 Passed | 0 Failed | 0 …
```
> Add mapper.policyToTargetRefObj() helper function

- pkg/deploy/lattice/target_group_manager.go
- pkg/deploy/lattice/target_group_manager_test.go
bug
#369 
Fix bug #369 by resetting the health check configuration to default setting if `healthCheck` section is removed
Manual testing, confirmed health check configuration is reset if removed. Also ran e2e tests
```
Ran 31 of 31 Specs in 2030.679 seconds
SUCCESS! -- 31 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestIntegration (2031.56s)
PASS
ok      github.com/aws/aws-application-networking-k8s/test/suites/integration   2031.595s
```
N/A
**Will …
> fix: reset to default settings if healthCheck is removed (#369)

- pkg/apis/applicationnetworking/v1alpha1/targetgrouppolicy_types.go
- pkg/apis/applicationnetworking/v1alpha1/vpcassociationpolicy_types.go
- pkg/gateway/model_build_targetgroup.go
- pkg/gateway/utils.go
- pkg/gateway/utils_test.go
- pkg/model/core/policy.go
Changes:
- Change getAttachedTargetGroupPolicy to a generic method `getAttachedPolicy()`
**Testing done on this change**: 
- Added extra unit tests
- e2etest WIP
```release-note
```
> Change getAttachedTargetGroupPolicy to a generic method `getAttachedPolicy()`

- pkg/deploy/lattice/targets_manager.go
- pkg/deploy/lattice/targets_manager_test.go
- pkg/deploy/lattice/targets_synthesizer.go
- pkg/gateway/model_build_targets.go
- test/suites/integration/httproute_creation_test.go
bug
#386 
This PR allows the controller to continue to create Lattice service, and listeners, and rules when there are no targets to register
Added unit tests, and e2e tests.
`make e2e-test` output:
```
Ran 32 of 32 Specs in 2332.975 seconds
SUCCESS! -- 32 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestIntegration (2334.12s)
PASS
ok      github.com/aws/aws-application-networking-k8s/test/suites/integration   2334.147s
```
Added test case `httproute_creation_test.go`
**Will this PR introduce any new …
> fix: create lattice resources when no endpoints in K8s services (#386)

- controllers/gateway_controller.go
- pkg/deploy/lattice/service_network_manager.go
- pkg/deploy/lattice/service_network_synthesizer_test.go
- pkg/gateway/model_build_service_network_test.go
- pkg/gateway/model_build_servicenetwork.go
- pkg/model/lattice/servicenetwork.go
**What type of PR is this?** feature
**Which issue does this PR fix**: #199  part of security group api support, this PR don't include targets_synthesizer.go changes, so this PR  will not pass security groups ids to the aws vpc lattice sdk, will do that in a next seperate PR
- Add extra unit tests
- e2etest all pass
```
Ran 31 of 31 Specs in 2239.955 seconds
SUCCESS! -- 31 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestIntegration (2240.27s)
PASS
```
**Will this break upgrades or downgrades. Has updating a running cluster been tested?**: No
**Does this PR introduce any user-facing …
> Read VpcAssociationPolicy value in the model_build_servicenetwork

- Makefile
- controllers/eventhandlers/gateway.go
- controllers/eventhandlers/gatewayclass.go
- controllers/gateway_controller.go
- pkg/deploy/lattice/listener_manager.go
- pkg/deploy/lattice/listener_manager_test.go
- pkg/deploy/lattice/listener_synthesizer.go
- pkg/deploy/lattice/listener_synthesizer_test.go
- pkg/deploy/lattice/rule_manager.go
- pkg/deploy/lattice/rule_manager_mock.go
- pkg/deploy/lattice/rule_manager_test.go
- pkg/deploy/lattice/rule_synthesizer.go
- pkg/deploy/lattice/rule_synthesizer_test.go
- pkg/deploy/stack_deployer.go
- pkg/deploy/stack_deployer_test.go
cleanup
#126 partially
- Removes use of glog in event handlers, listener and rule manager, and listener synthesizer
- Removes unnecessary logs, such as in the case of log n throw
- Cleans output of logs so that they contain less clutter, are grammatically correct, and specify more useful information
- General code cleanliness
- Re-adds `e2e-test` and `e2e-clean` to `make help` output, which appear to have been inadvertently removed?
```
Ran 32 of 32 Specs in 2139.930 seconds
SUCCESS! -- 32 Passed | 0 Failed …
```
> Logging Cleanup - Part 1

- controllers/gateway_controller.go
- pkg/aws/cloud.go
- pkg/aws/gomock_reflect_3295326204/prog.go
- pkg/aws/gomock_reflect_3994833575/prog.go
- pkg/deploy/externaldns/dnsendpoint_manager.go
- pkg/deploy/externaldns/dnsendpoint_manager_test.go
- pkg/deploy/lattice/listener_manager.go
- pkg/deploy/lattice/listener_synthesizer.go
- pkg/deploy/lattice/rule_synthesizer.go
- pkg/deploy/lattice/service_network_manager.go
- pkg/deploy/lattice/service_network_manager_mock.go
- pkg/deploy/lattice/service_network_manager_test.go
- pkg/deploy/stack_deployer.go
cleanup
#126 partially
- Removes use of glog in dnsendpoint, listener, and service network managers, and listener synthesizer
- Removes unnecessary logs, such as in the case of log and throw
- Add checks for errors before logging errors
- Cleans output of logs so that they contain less clutter, are grammatically correct, and specify more useful information
- General code cleanliness
```
Ran 32 of 32 Specs in 2170.862 seconds
SUCCESS! -- 32 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestIntegration (2172.09s)
PASS
ok …
```
> Logging Cleanup - Part 2

- controllers/route_controller.go
- controllers/serviceexport_controller.go
- controllers/serviceimport_controller.go
- pkg/deploy/lattice/listener_manager.go
- pkg/deploy/lattice/listener_synthesizer.go
- pkg/deploy/lattice/rule_synthesizer.go
- pkg/deploy/lattice/target_group_synthesizer.go
- pkg/gateway/model_build_lattice_service.go
- pkg/gateway/model_build_listener.go
- pkg/gateway/model_build_rule.go
- pkg/gateway/model_build_targetgroup.go
Cleanup
#126 (final)
- Removes many unwanted info logs
- Changes some error logs that do not actually indicate an error (e.g. expected errors that result in requeue) to debug
- Removes struct embedding and use of ambiguous %v in logs
- Add route reconciler info logs that match the other reconcilers
- General logging language/clarity improvements
- Added some missing error handling
- Overall, running this with only info level logs should be way easier to follow along, and running with debug logs should be much less noisy without losing relevant/useful context
**Testing …
> Logging Cleanup - Part 5

- docs/reference/vpc-association-policy.md
- mkdocs.yml
> Add VpcAssociationPolicy doc

- test/pkg/test/framework.go
- test/suites/integration/suite_test.go
- test/suites/integration/vpc_association_policy_test.go
**What type of PR is this?** e2e test cases for the security group api feature #199 
**What does this PR do / Why do we need it**: e2e test cases for the security group api feature #199 
**Automation added to e2e**: Add VpcAssociationPolicy e2e test cases, whole test suite pass
```
Ran 34 of 34 Specs in 2230.206 seconds
SUCCESS! -- 34 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestIntegration (2230.52s)
PASS
```
```release-note
```
By submitting …
> Create VpcAssociationPolicy e2e test

- pkg/deploy/lattice/config_test.go
- pkg/deploy/lattice/listener_manager.go
- pkg/deploy/lattice/listener_manager_test.go
- pkg/deploy/lattice/rule_manager.go
- pkg/deploy/lattice/rule_manager_test.go
- pkg/deploy/lattice/service_manager.go
- pkg/deploy/lattice/service_network_manager.go
- pkg/deploy/lattice/service_network_manager_test.go
- pkg/deploy/lattice/target_group_manager.go
- pkg/deploy/lattice/target_group_manager_test.go
Note:
Add default tags to all lattice resources (managers). Major change in managers. Test changes are mostly layout and cloud mock removal.
closes #392
> add default tags to all lattice resources

- docs/deploy.md
- helm/templates/configmap.yaml
- helm/templates/deployment.yaml
- helm/values.yaml
**What type of PR is this?** Fix #435 
Referred that PR https://github.com/aws/aws-application-networking-k8s/pull/264
```release-note
```
> Add ability to pass CLUSTER_NAME env variable in helm chart

- cmd/aws-application-networking-k8s/main.go
- controllers/iamauthpolicy_controller.go
Note:
Add dummy controller for IAM Auth Policy. Policy can be attached to Lattice Service Network or Service. We support only Gateway, HTTP and GRPC routes as target references right now. I will split reconciliation into Gateway and Route types.
Partly #18
> add IAM Auth Policy dummy controller

- docs/deploy.md
- helm/templates/configmap.yaml
- helm/templates/deployment.yaml
- helm/values.yaml
feature
N/A
- Adds ability to override VPC Lattice endpoint when using helm
N/A
N/A
No
No
No
```release-note
```
> Added ability to override LATTICE_ENDPOINT env variable with helm

- controllers/accesslogpolicy_controller.go
- pkg/deploy/lattice/access_log_subscription_manager.go
- pkg/deploy/lattice/access_log_subscription_manager_mock.go
- pkg/deploy/lattice/access_log_subscription_manager_test.go
- pkg/deploy/lattice/access_log_subscription_synthesizer.go
- pkg/deploy/lattice/access_log_subscription_synthesizer_test.go
- test/suites/integration/access_log_policy_test.go
feature
#200 partially
- Enables support for updating Access Log Policies (ALPs)
- When an ALP is updated to have a different `destinationArn` of the same destination type (i.e. S3 Bucket, CloudWatch Log Group, or Firehose Delivery Stream), the underlying Access Log Subscription (ALS) is updated
- When an ALP is updated to have a different `destinationArn` of a different destination type, a new ALS is created to replace it, then the previous one is deleted
- When an ALS is replaced, the ALP's `VpcLatticeAccessLogSubscription` annotation is updated with the new ARN
- When an ALP is updated to have a different `targetRef`, a new ALS is created to replace the existing one, then the …
> Added Support for Updating Access Log Policies

- cmd/aws-application-networking-k8s/main.go
- controllers/iamauthpolicy_controller.go
- pkg/aws/services/vpclattice.go
- pkg/aws/services/vpclattice_mocks.go
- pkg/deploy/lattice/iamauthpolicy_manager.go
- pkg/deploy/lattice/iamauthpolicy_manager_test.go
- pkg/model/lattice/iamauthpolicy.go
- pkg/utils/gwlog/gwlog.go
Note:
Add model and manager for IAM Auth Policy. Currently handles only happy path when SN or Svc exists. If Lattice targetRef does not exists will print NotFound exceptions and retry later.
Always change AuthPolicy for Sn and Svc to AWS_IAM on upsert.
Tests:
Created SN and Svc in Lattice console. Applied and deleted `examples/iam-auth-policy-example.yaml` for SN and Svc.
> add IAM Auth Policy create/update/delete

- pkg/utils/gwlog/gwlog.go
Note:
Switch to ISO8601 for production logs. Debug logs are ISO8601.
Currently prod is Unix epoch timestamp:
debug: `2023-10-25T18:07:38.698-0700	INFO	controller.gateway-class`
prod: `{"level":"info","ts":1698340801.9449012,"logger":"controller.gateway-class"`
New prod log: `{"level":"info","ts":"2023-10-26T10:54:35.722-0700","logger":"controller.gateway"`
> use ISO8601 for production logs

- config/iam/recommended-inline-policy.json
- controllers/accesslogpolicy_controller.go
- controllers/gateway_controller.go
- controllers/route_controller.go
- controllers/service_controller.go
- controllers/serviceexport_controller.go
- controllers/serviceimport_controller.go
- docs/deploy.md
- docs/reference/access-log-policy.md
- examples/recommended-inline-policy.json
- mkdocs.yml
- pkg/apis/applicationnetworking/v1alpha1/accesslogpolicy_types.go
- pkg/k8s/utils.go
- Adds documentation for the new Access Log Policy CRD
- Modifies the Access Log Subscription annotation applied to the policies such that it has a prefix, as per [Kubernetes requirements](https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/#:~:text=Syntax%20and%20character%20set)
- Adds permissions required to use Access Log Policies and VPC Association Policies to examples and documentation
- Adds a top-level info log of any error that causes a reconciler to requeue a request
Example logs:
```
2023-10-26T13:37:49.488-0700    INFO    controller.access-log-policy    controllers/accesslogpolicy_controller.go:107   reconcile       {"name": "test-policy"}
2023-10-26T13:41:39.047-0700    INFO    controller.access-log-policy …
```
> Access Log Policy API Reference, Annotation Prefixes, Permissions Docs, and Logging Improvements

- test/pkg/test/framework.go
- test/pkg/test/target_group_policy.go
- test/suites/integration/target_group_policy_test.go
**What type of PR is this?** test
**Which issue does this PR fix**: #379
**What does this PR do / Why do we need it**: add e2e tests for Target Group Policy CRD
`make e2e-test` outputs:
```
Ran 38 of 38 Specs in 2715.256 seconds
SUCCESS! -- 38 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestIntegration (2716.14s)
PASS
ok      github.com/aws/aws-application-networking-k8s/test/suites/integration   2716.173s
```
**Automation added to e2e**: add `test/suites/integration/target_group_policy_test.go`  …
> test: add e2e tests for Target Group Policy CRD

- controllers/iamauthpolicy_controller.go
Note:
add IAM auth policy conflicts handling
Tested manually by creating multiple policies for same target ref.
Log example:
```
2023-10-27T13:19:32.780-0700	ERROR	controller.iam-auth-policy	controllers/iamauthpolicy_controller.go:52	conflict with other policies for same TargetRef, policy: test-iam-auth-policy, conflicted with: [test-iam-auth-policy2]
```
Policy Status updated:
```
Status:
Conditions:
Last Transition Time:  2023-10-27T20:13:30Z
Message:
Observed Generation:   1
Reason:                Conflicted
Status:                False
Type:                  Accepted
```
> add iam auth policy conflict handling

- controllers/accesslogpolicy_controller.go
- helm/templates/cluster-role-controller.yaml
- pkg/k8s/events.go
- pkg/k8s/utils.go
Feature
N/A
- Adds missing helm permission for AccessLogPolicy/status
- Adds event publishing for AccessLogPolicy resources
e2e tests will be updated in a followup PR
No
No
No
```release-note
```
> Added events to Access Log Policy and fixed missing helm permission

- controllers/accesslogpolicy_controller.go
- pkg/gateway/model_build_access_log_subscription.go
- pkg/gateway/model_build_access_log_subscription_test.go
bug
N/A
Currently, when an Access Log Policy (ALP) has its spec changed such that it becomes invalid, it cannot be deleted because the controller validation short circuits to setting the ALP status to Invalid and doesn't remove finalizers nor delete the underlying Access Log Subscription (ALS).
This change removes the short circuit from the deletion logic so that ALPs with invalid specs and their underlying ALS can be deleted.
1. Create valid ALP
- ALP status should be Accepted
3. Update ALP spec to have invalid Group (e.g. `foo`) or no `destinationArn` in `targetRef`
- …
> Fixed deletion of invalid Access Log Policies

- .github/dependabot.yml
Enabling Dependabot for monthly minor version updates on all dependencies except Gateway API
> Enabled Dependabot for monthly minor version updates

- pkg/deploy/lattice/iamauthpolicy_manager.go
Note:
If we enable IAM without any policy attached it will reject all traffic until policy applied. 
To avoid temporary traffic rejection we first apply policy and then enable IAM auth.
> change iam auth policy creation order put policy, enable IAM

- controllers/serviceexport_controller.go
- test/suites/integration/serviceexport_mutation_test.go
**Which issue does this PR fix**: #477 
Added a new e2e test, new test can pass
Did following manual test:
1. kubectl apply -f examples/inventory-ver2.yaml (which includes a Deployment and a Service)
2. kubectl apply -f examples/inventory-ver2-export.yaml (which includes a ServiceExport)
3. VPC Lattice target group and its targets created as expected
4. do `kubectl get endpoints inventory-ver2`, all endpoints IP addresses == target group's targets IP addresses
5. do `kubectl rollout restart deployment inventory-ver2` to re-create all pods of inventory-ver2
6. do kubectl get endpoints inventory-ver2, all endpoints IP …
>  BugFix: ServiceExport controller  should handle Pods IPs Mutation

- .github/workflows/presubmit.yaml
- hack/toolchain.sh
Fixes #N/A
**Description**
* Update to use https://github.com/mattn/goveralls directly
**How was this change tested?**
* `make presubmit`
**Does this change impact docs?**
> ci: Use specific commit of mattn/goveralls instead of shogo821/goveralls

- pkg/deploy/lattice/target_group_synthesizer.go
Remove deleting 5 min and older target group logic in the `calculateTargetGroupsToDelete()`
This code is originally used as a kind of backward compatible change for the Lattice Target Group naming breaking change(Target Group Ownership change), however, this code cause a bug when doing the performance test: 
When the controller is trying to synthesize lots of lattice services and target groups, in the middle of reconciliation, it has one time that many target groups are created but don't have lattice service's route reference it. This code logic could wrongly recognize  that this target group need to be deleted, but actually should not.
> Bugfix: Remove deleting 5 min old and older TG logic

- docs/deploy.md
- docs/developer.md
- golangci.yaml
documentation
This change to the documentation references the prefix list ID directly when configuring Security Groups so they can be dynamically updated when the prefix list entries in them change.
**Which issue does this PR fix**: #455 
If the underlying IP range changes, traffic will be impacted to security groups that are not referencing the prefix list ID on the security group.
Run a fresh controller deployment using the documentation
No
Yes
```release-note
This change to the documentation references the prefix list ID directly when …
```
> Docs: Update Docs to reference IPv4 and IPv6 Prefix lists IDs directly when configuring Security Groups

- test/suites/integration/deregister_targets_test.go
> Fix deregister_targets e2etest

- controllers/iamauthpolicy_controller.go
- test/pkg/test/framework.go
- test/suites/integration/iamauthpolicy_test.go
Note:
- add finalizer to iam auth policy before calling lattice
- add more assertions to e2e tests
- k8s annotations
- lattice auth type and policy are set to correct values
```sh
IAM Auth Policy GroupName Error
/Users/mhlbrz/workplace/aws-application-networking-k8s/test/suites/integration/iamauthpolicy_test.go:128
2023-11-10T14:22:24.877-0800	INFO	test/framework.go:223	Creating objects: *v1.Deployment/ratme-1-tnntyy59m5, *v1.Service/iam-auth-http, *v1beta1.HTTPRoute/iam-auth-http
• [1.191 seconds]
IAM Auth Policy Kind Error
/Users/mhlbrz/workplace/aws-application-networking-k8s/test/suites/integration/iamauthpolicy_test.go:134
• [1.140 seconds]
IAM Auth Policy TargetRef Not Found …
```
> add more assertions to iam auth policy e2e test

- docs/reference/iam-auth-policy.md
> Add IAMAuthPolicy doc

- pkg/deploy/lattice/listener_synthesizer.go
- pkg/deploy/lattice/listener_synthesizer_test.go
- pkg/deploy/lattice/rule_manager.go
- pkg/deploy/lattice/rule_manager_test.go
- pkg/deploy/lattice/rule_synthesizer.go
- pkg/deploy/lattice/rule_synthesizer_test.go
- pkg/gateway/model_build_listener.go
- pkg/gateway/model_build_rule.go
- pkg/gateway/model_build_rule_test.go
- pkg/gateway/model_build_targetgroup.go
- pkg/gateway/model_build_targetgroup_test.go
- pkg/model/lattice/listener.go
- pkg/model/lattice/rule.go
- test/pkg/test/framework.go
- test/suites/integration/delete_target_groups_test.go
bug fix
#493 
First, this PR aligns the implementation more with the gateway spec for invalid backendRefs. With this change, invalid backendRefs will either be omitted when another backendRef exists that is valid or will configure the rule to return a 404. 
Second, when building listener model objects, we will no longer create model objects for deleted listeners. As I was making this change, I simplified the listener logic that was tracking deletes. Since we never actually delete listeners and they are deleted when the service is deleted, I've removed the unneeded code.
***Manual Testing***
The following shows adding a route with an invalid …
> Return 404 for invalid backendRefs

- controllers/gateway_controller.go
- controllers/vpcassociationpolicy_controller.go
- docs/configure/environment.md
- docs/conformance-test.md
- docs/developer.md
- pkg/aws/services/vpclattice.go
- pkg/config/controller_config.go
- pkg/config/controller_config_test.go
- pkg/deploy/lattice/service_network_manager.go
- pkg/deploy/lattice/service_network_manager_mock.go
- pkg/deploy/lattice/service_network_manager_test.go
- pkg/gateway/model_build_lattice_service.go
feature
* Add DEFAULT_SERVICE_NETWORK env variable, on cluster startup create service network and associate VPC
* Keeps CLUSTER_LOCAL_GATEWAY behavior (for conformance test) with new network override mode, unlike CLUSTER_LOCAL_GATEWAY, register all gateways to the same default service network.
```release-note
```
By …
> Provide default gateway setup

- cmd/aws-application-networking-k8s/main.go
- controllers/vpcassociationpolicy_controller.go
- pkg/deploy/lattice/service_network_manager.go
- pkg/deploy/lattice/service_network_manager_test.go
- pkg/deploy/lattice/target_group_manager.go
- pkg/deploy/lattice/target_group_manager_test.go
- test/pkg/test/framework.go
- test/suites/integration/byoc_test.go
- test/suites/integration/defined_target_ports_test.go
- test/suites/integration/delete_target_groups_test.go
- test/suites/integration/httproute_creation_test.go
- test/suites/integration/httproute_header_match_test.go
- test/suites/integration/httproute_mutation_do_not_leak_target_group_test.go
- test/suites/integration/httproute_path_match_test.go
- test/suites/integration/httproute_update_test.go
- test/suites/integration/iamauthpolicy_test.go
- test/suites/integration/serviceexport_mutation_test.go
- test/suites/integration/suite_test.go
- test/suites/integration/target_group_policy_test.go
- test/suites/integration/vpc_association_policy_test.go
bug
* Use strongly consistent list call on ListTargetGroups, fixes target group leaking issue (which seems to happen more often when we have a lot of existing target groups)
* Correctly handle when there are multiple target groups matching tags in findTargetGroup(). This can happen in the middle of TG protocol update, etc. Target groups only become unique after matching more fields including protocol. Changed related e2e test to make sure unused target groups are getting replaced by this logic.
* Fix wrong e2e test cases on delete_target_group_test, deleting a deployment still results in target deregistration as it does not delete service.
* Fix bug where e2e test will pick up existing other hosted zone and delete it
* Made a …
> Fix target group leaking and e2etest

- docs/deploy.md
- helm/templates/configmap.yaml
- helm/templates/deployment.yaml
- helm/values.yaml
- test/suites/integration/suite_test.go
- fix e2e test issue
```release-note
```
> Pass defaultServiceNetwork env variable

- docs/api-types/target-group-policy.md
- docs/concepts/index.md
- docs/concepts/overview.md
- docs/guides/deploy.md
- docs/guides/getstarted.md
- docs/guides/multi-sn.md
- mkdocs.yml
documentation
Documentation build is currently failing due to broken links. Also, I'm running a markdown formatter for consistent line spacing and formatting.
> doc: fix doc build

- examples/my-hotel-gateway-tls.yaml
- examples/parking-route-path.yaml
- examples/second-account-gw1-full-setup.yaml
- examples/tls-route-with-own-cert.yaml
- pkg/aws/services/tagging.go
- pkg/gateway/model_build_rule.go
- pkg/gateway/model_build_rule_test.go
- test/pkg/test/framework.go
- test/pkg/test/gateway.go
- test/pkg/test/header_match_httproute.go
- test/pkg/test/method_match_httproute.go
- test/pkg/test/path_match_httproute.go
- test/pkg/test/weighted_routing_httproute.go
- test/suites/integration/byoc_test.go
bug
Partially - #469 
Changed behavior for empty matches in rules. They had default value in the past but they don't right now.
https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io%2fv1.HTTPRouteRule
https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1alpha2.GRPCRouteRule
Fixed our examples to be compatible with latest GWAPI CRDs.
* HTTPRoute/GRPCRoute - All Service backendRefs require ports
* Gateway - HTTPS listeners must have TLS section
* Gateway - TLS section must include at least one cert when mode is `Terminate`
* This is a tricky part, I had to add dummy fields on our examples. It looks ugly but probably okay.
* Gateway - …
> Fix e2e tests and examples to be compatible w/ latest CRDs

- config/crds/bases/application-networking.k8s.aws_targetgrouppolicies.yaml
- docs/api-reference.md
- examples/deploy-v0.0.18.yaml
- pkg/apis/applicationnetworking/v1alpha1/targetgrouppolicy_types.go
documentation
Fixes a typo in TargetGroupPolicy that accidentally referred to AccessLogPolicy
> Doc: Update Target Group Policy documentation

- docs/contributing/developer.md
- pkg/aws/services/vpclattice.go
- pkg/aws/services/vpclattice_mocks.go
- pkg/deploy/lattice/service_manager.go
- pkg/deploy/lattice/service_manager_test.go
bug fix
n/a
Target group deletion following service deletion is hitting a race condition where the target group is still considered associated to the service via a listener. This PR removes listeners explicitly prior to service deletion, which should ensure TGs for the service are free to delete.
Race condition sometimes occurs running GRPC end-to-end tests.
updated unit tests
ran GRPC test
no
**Will this break upgrades or downgrades. Has updating a running …
> Fix for leaking target groups on service delete

- Makefile
- cmd/aws-application-networking-k8s/main.go
- docs/guides/environment.md
- helm/templates/configmap.yaml
- helm/templates/deployment.yaml
- helm/values.yaml
- pkg/utils/gwlog/gwlog.go
- scripts/load_env_variables.sh
- test/suites/integration/suite_test.go
Note:
- Decouple log-level from dev and prod logging config. Can use different logging levels for both.
- Add env variable to control log level. Introduce few levels: **info**, **debug**, **error**, **panic**. Default value is **info**. Still thinking about error and panic logs, probably redundant.
- Add DEV_MODE env variable to enable development logging format.
#530
> add log level env variable and update helm

- docs/api-types/grpc-route.md
- docs/api-types/http-route.md
- docs/api-types/service-export.md
- docs/api-types/service-import.md
- mkdocs.yml
documentation
#401 
```release-note
```
> Add service export/import documentations

- pkg/controllers/gateway_controller.go
- pkg/controllers/route_controller.go
- pkg/controllers/route_controller_test.go
- pkg/deploy/lattice/service_network_manager.go
- pkg/model/core/grpcroute.go
- pkg/model/core/httproute.go
- pkg/model/core/route.go
Note:
Add Gateway API Spec validations to route controller. Reconciler will return non-retryable error when Spec is not valid.
Spec is not valid if there is at least single invalid property in ParentRef or BackendRef.
Tests:
- manually tested with #544 scenario
- unit test - partly covered by existing unit test - happy path
- e2e test - in progress
Example for new status:
```
Status:
Parents:
Conditions:
Last Transition Time:  2023-12-07T19:32:33Z
Message:
Observed Generation:   5
Reason:                Accepted
Status:                True
Type:                  Accepted
Last Transition Time:  2023-12-07T19:32:33Z
Message:               backendRef name: inventory-ver1
Observed Generation:   5
Reason:                BackendNotFound
Status:                False
Type: …
```
> update validations and status on route reconciler

- .gitignore
- scripts/lib/login.sh
- scripts/release-controller.sh
- Shift from buildah to `docker build` so that people could be more easier to release image in their macOS, (docker build also work in linux in the image release ec2 instance) (buildah only have linux but no macOS version, and [aws-load-balancer-controller](https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/Makefile#L100) also use the docker build) (at least, for me, do image release in my macOS save 15 min time)
- Hard code the ECR_PUBLISH_ROLE_ARN in release-controller.sh, as the "public.ecr.aws/aws-application-networking-k8s/aws-gateway-controller" ECR repo only exists in 606627242267, and people who do image release must assume this role
Use the new release-controller.sh, manually changed all image version to `v0.0.0-release-test`, run the …
> Shift from buildah to docker build so that people could more easier release image in their local macOS

- Makefile
- scripts/github-release.sh
- scripts/lib/common.sh
- Add a github release automation script (use the steps in our internal release doc as reference)
Run this script from my local ` RELEASE_VERSION=v1.0.2  ./scripts/github-release.sh`, using this script did the v1.0.2 github release, it's able to push release branch, tag and send a PR 
In the future, probably this script can be triggered by github action and run in github action worker instance
> Add a github release automation script

- pkg/deploy/lattice/target_group_synthesizer.go
- pkg/deploy/lattice/target_group_synthesizer_test.go
- pkg/deploy/stack_deployer.go
- pkg/deploy/stack_deployer_test.go
Note:
Address performance issue for unused target group cleanup. Implemented background garbage collector, that runs every X seconds. Might need to tune timers after. 
e2e tests pass:
```
Ran 58 of 58 Specs in 2358.172 seconds
SUCCESS! -- 58 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestIntegration (2358.17s)
```
close #552
> Add TG garbage collector

- test/pkg/test/framework.go
- test/suites/integration/access_log_policy_test.go
- test/suites/integration/ram_share_test.go
- test/suites/integration/suite_test.go
cleanup
N/A
- Removes requirement for Cluster VPC Association to Gateway Service Network to be tagged with "ManagedBy"
- Controller no longer manages this association, so the tag should not be expected to be there
- Changes the logic of resource naming in Access Log Policy e2e tests such that all AWS resources are created with a partially pseudo-random name
- Prevents previously leaked resources from interfering with new test runs due to name conflicts
- Changes the logic of Access Log Policy e2e tests to tag all AWS resources with TestSuite=access-log-policy and then to clean up all AWS resources with that tag in the AfterAll block
- Subsequent test runs can clean up resources …
> Access Log Policy Test Cleanup Robustness

- pkg/deploy/lattice/target_group_manager.go
- pkg/deploy/lattice/target_group_manager_test.go
bug
Fixes target group discovery logic that may cause service exports from other clusters are not shown.
I think this VPC-based filtering logic got into during the TG performance optimization. I don't think this adds a lot of performance value anyways so I completely removed it. List() call is currently used in two places:
* Unused target group cleanup. This filters result by VPC regardless.
* ServiceExport detection. This will now be fixed.
Unit testing and manual cross-cluster testing that verifies traffic. …
> Fix target group discovery logic

- scripts/github-release.sh
- scripts/lib/common.sh
Improve github-release.sh, delete local release branch/ tag if it exist, show error message if release branch/ tag  exists remotely
> Improve github-release.sh

- docs/guides/deploy.md
documentation
n/a
Content of [examples/ipv6-cluster.yaml](https://github.com/aws/aws-application-networking-k8s/blob/main/examples/ipv6-cluster.yaml) is for `eksctl` but not `kubectl`.
https://github.com/aws/aws-application-networking-k8s/blob/26e82404f79492994527386b5b5f6fe0f0d63014/docs/guides/deploy.md?plain=1#L121-L122
https://github.com/aws/aws-application-networking-k8s/blob/26e82404f79492994527386b5b5f6fe0f0d63014/examples/ipv6-cluster.yaml#L1-L25
n/a …
> Fix incorrect cluster create command

- pkg/deploy/lattice/service_manager.go
- pkg/deploy/lattice/service_manager_test.go
- pkg/deploy/lattice/service_network_manager.go
- pkg/deploy/lattice/service_synthesizer.go
bug 
In the scenario where
- account A is managed by the lattice controller
- account A shares a service to account B
- account B associates this service to its own service network
Account A can be in a situation where does not have permissions to read the tags of that association
Therefore this results in an error during route reconciliation. 
```
error during service synthesis failed ServiceManager.Upsert xxx due to NotFoundException: Resource was not found
status code: 404, request id: a400c824-64e3-4694-94ce-1b5698e1ee35
```
if the get tags of a service network association request fails, instead of erroring, skip deleting the association and log.
**If an issue # is not …
> In service_manager, if tags of an association cannot be fetched, skip instead of error

- cmd/aws-application-networking-k8s/main.go
- config/rbac/cluster-role-controller.yaml
- helm/templates/cluster-role-controller.yaml
- pkg/controllers/eventhandlers/mapper.go
- pkg/controllers/eventhandlers/service.go
- pkg/controllers/route_controller.go
- pkg/controllers/route_controller_test.go
- pkg/controllers/serviceexport_controller.go
- pkg/deploy/lattice/targets_manager.go
- pkg/deploy/lattice/targets_manager_test.go
- pkg/gateway/model_build_targets.go
- pkg/gateway/model_build_targets_test.go
- pkg/model/lattice/targets.go
feature
Not yet - this is an initiation for pod readiness support project.
* Record pod readiness on targets model builder
* Listen to endpointslice event, has multiple benefits:
* has advanced read of status
* can scale to 1000+ pods, old endpoint objects have limits on 1000 addresses
* Keep the old behavior yet - non-ready targets are filtered at targets manager. this will be changed on the next PR.
Splitting PR to keep reviewability.
**Will this break …
> Listen to endpointslice event

- .github/workflows/e2e-test.yaml
- Makefile
- cmd/aws-application-networking-k8s/main.go
- config/manager/manager.yaml
- docs/guides/environment.md
- docs/guides/pod-readiness-gates.md
- helm/templates/_helpers.tpl
- helm/templates/deployment.yaml
- helm/templates/webhook.yaml
- helm/values.yaml
- pkg/config/controller_config.go
- scripts/gen-webhook-secret.sh
- scripts/patch-deploy-yaml.sh
feature
https://github.com/aws/aws-application-networking-k8s/issues/596
1. Updates Helm install to include pod readiness gate webhook.
2. For manual installs, defers cert generation to install time and does NOT enable webhook by default
3. New scripts in ```scripts/``` to provision webhook TLS certificate and enable the webhook 
4. Include ```webhook-e2e-test``` in github workflow
5. Doc updates
Since the controller cannot start without a valid TLS secret in place AND we cannot provision a cert at build time without confusing github with "secret" material, we now disable the webhook by default for manual installs using ```deploy.yaml```. Instead, I have created new scripts …
> Update Helm chart to include pod mutating webhook for readiness gates

- pkg/k8s/policyhelper/kind.go
- pkg/k8s/policyhelper/policy.go
feature
Allow targetgroup policy being attached to a serviceExport object.
Today, there is no way to configure target group policy for target group reconciled from serviceExport CRD.
make presubmit pass
no
no
```release-note
```
By submitting this pull request, I confirm that my contribution is made under the terms of the …
> Allow targetgroup policy attached to serviceExport

- Makefile
- cmd/aws-application-networking-k8s/main.go
- pkg/controllers/eventhandlers/mapper.go
- pkg/controllers/eventhandlers/mapper_test.go
- pkg/webhook/core/mutating_handler.go
- pkg/webhook/core/mutating_handler_test.go
- pkg/webhook/core/mutator.go
- pkg/webhook/pod_mutator.go
- pkg/webhook/pod_mutator_test.go
- pkg/webhook/pod_readiness_gate_injector.go
- test/pkg/test/framework.go
- test/pkg/test/httproute.go
- test/pkg/test/nginxapp.go
- test/suites/webhook/readiness_gate_inject_test.go
- test/suites/webhook/suite_test.go
bug fix
#623 
Validates the pod requires the readiness gate before adding it. Readiness gates are added to pods where
1. The pod is referenced by a service's selector
2. That service is referenced by a HTTPRoute, GRPCRoute, or ServiceExport
3. The route has a parentRef to a VPC Lattice gateway
Under these conditions, it is assumed the pod will be a member of a Lattice target group and the readiness gate is added. All other pods will not receive the readiness gate. 
Other minor issues addressed:
* small conformance issue in ```mapper.go``` and ```route_controller.go```
* use standardize logger for ```mutating_handler.go``` 
Added extensive unit tests …
> Conditionally inject pod readiness gates

- .github/workflows/e2e-test.yaml
- scripts/github-release.sh
**Which issue does this PR fix**:bug
**What does this PR do / Why do we need it**: Rename file in `e2e-test.yaml` after #630 
**If an issue # is not available please add repro steps and logs from aws-gateway-controller showing the issue**: [e2e-test is failing ](https://github.com/aws/aws-application-networking-k8s/actions/runs/8992764883/job/24703263870)
**Testing done on this change**:N/A
**Automation added to e2e**: N/A
**Will this PR introduce any new dependencies?**:No
**Will this break upgrades or downgrades. Has updating a running cluster been tested?**: No
**Does this PR introduce any user-facing change?**:No
```release-note
```
> Fix file rename in e2e test script and fix tag check in release script

- .github/workflows/publish-doc.yaml
- docs/contributing/developer.md
- docs/overrides/home.html
- mkdocs.yml
- requirements.txt
- scripts/github-release.sh
- Use  "mike" to managed mkdoc generated public doc versioning. https://github.com/jimporter/mike
- Enable versioning in the "Material for MkDocs" https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/
- Need to deprecate the aws amplify CI pipeline to build doc website in the 094684711435 account, use "github Action" `publish-doc.yaml`, to build and deploy public doc instead. Referenced other open source project on how they generate doc: e.g. https://github.com/tvdboom/ATOM/tree/master, https://github.com/pydantic/pydantic
Old and new ways of mkdoc build and deploy flow:
every time when we push code with doc update, the one aws amplify CI pipeline in the 094684711435 will ingest that change and build the main branch code then pack the artifact, amplify.yml for that CI …
> Control public doc versioning by "mike"

- README.md
- config/manager/kustomization.yaml
- docs/guides/deploy.md
- files/controller-installation/deploy-v1.0.6.yaml
- helm/Chart.yaml
- helm/values.yaml
> Release artifacts for v1.0.6

- docs/guides/environment.md
- helm/templates/deployment.yaml
- helm/values.yaml
bug
#653 
The `DISABLE_TAGGING_SERVICE_API` environment variable was not able to be set in the Helm chart
tested manually
```release-note
```
> Add `DISABLE_TAGGING_SERVICE_API` env to helm chart

- docs/guides/getstarted.md
documentation
You encounter an error in AWS Gateway API Controller after deploying the gateway. The logs indicate that there are missing permissions for tlsroutes in ClusterRole. 
Logs from AWS Gateway API Controller pod: 
Error: E0904 23:06:10.238076 1 reflector.go:147] pkg/mod/k8s.io/client-go**@v0.28.3/tools/cache/reflector.go:229:** Failed to watch *v1alpha2.TLSRoute: failed to list *v1alpha2.TLSRoute: tlsroutes.gateway.networking.k8s.io is forbidden: User "system:serviceaccount:aws-application-networking-system:gateway-api-controller" cannot list resource "tlsroutes" in API group "gateway.networking.k8s.io" at the cluster scope
There is a difference in version of AWS Gateway …
> Corrected the verion of gateway api controller

- docs/guides/https.md
documentation
Fixed word typo from `parertRefs` to `parentRefs`.
Documentation consistency.
N/A
N/A
N/A
N/A
N/A
```release-note
```
> fix(docs/guides/https.md): fixing word typo

- docs/guides/environment.md
- helm/templates/deployment.yaml
- helm/values.yaml
- pkg/config/controller_config.go
- pkg/config/controller_config_test.go
- pkg/controllers/route_controller.go
- pkg/deploy/stack_deployer.go
- pkg/utils/gwlog/actions.go
Feature/Improvement
#671 
Adds a configurable value for the number of max workers for route controller instances. Note this worker count applies to each route type: HTTP, GRPC, and TLS. This change also updates locking mechanism for target group garbage collection to be more performant and allow parallel execution for route reconciliation.
Created 50 HTTP routes. On start or change, all 50 are reconciled. Previously with max workers = 1 (default), the reconciliation rate was 1/s and total time was roughly 50s. For 5 workers, the rate was closer to 5/s, and total time was around 12s. When set to very large numbers (e.g. 25 or 100), the controller …
> Add configurable max workers for route controller instances

- .github/workflows/e2e-test.yaml
bug
#638 
Fixes `e2e-test.yaml` now that gateway CRDs are no longer packaged in the build.
n/a
n/a
No
n/a
No
> Fix for CRD install during e2e-test workflow

- docs/api-types/gateway.md
- docs/api-types/grpc-route.md
- docs/api-types/http-route.md
- docs/api-types/service-import.md
- docs/contributing/developer.md
- docs/guides/custom-domain-name.md
- docs/guides/getstarted.md
- docs/guides/grpc.md
- docs/guides/https.md
- docs/guides/tls-passthrough.md
- docs/guides/upgrading-v1-0-x-to-v1-1-y.md
- files/examples/greeter-grpc-route.yaml
- files/examples/inventory-route-bluegreen.yaml
- files/examples/inventory-route.yaml
- files/examples/my-gateway-tls-passthrough.yaml
- files/examples/my-gateway.yaml
- files/examples/my-hotel-gateway-multi-listeners.yaml
- files/examples/my-hotel-gateway.yaml
- files/examples/my-httproute.yaml
- files/examples/rate-route-path.yaml
- mkdocs.yml
documentation
#638 
Documentation and example updates now that we're building against Gateway API v1.2
Generated documentation against my branch/repo.
https://erikfuller.github.io/aws-application-networking-k8s/v0.0.0/guides/deploy/
https://erikfuller.github.io/aws-application-networking-k8s/v0.0.0/guides/upgrading-v1-0-x-to-v1-1-y/
n/a
n/a
Documentation updates
By submitting this pull request, I confirm that my contribution is made …
> Doc udpates for Gateway API v1.2 CRDs

- docs/faq.md
- docs/guides/deploy.md
- docs/guides/getstarted.md
- docs/guides/upgrading-v1-0-x-to-v1-1-y.md
Feature
#687
This adds additional details regarding users to install Gateway API CRDs themselves post `v.1.0.x`.
N/A
N/A
No.
N/A
N/A
```release-note
Improve v1.0.x upgrade guidance with CRD details
```
> Improve v1.0.x upgrade guidance with CRD details

- cmd/aws-application-networking-k8s/main.go
Feature
https://github.com/aws/aws-application-networking-k8s/issues/660
This PR adds a feature that pre-checks the required CRDs for the controller.
If the required CRDs are not installed, the controller will fail fast.
Tested by deploying the changes in my EKS cluster.
If the required CRDs are not installed, the controller logs the following message:
```
{"level":"info","ts":"2025-01-01T04:23:53.272Z","caller":"workspace/main.go:161","msg":"log level set to debug"}
...
{"level":"info","ts":"2025-01-01T04:23:53.272Z","logger":"setup","ca …
```
> Add check required crds

- .github/workflows/e2e-test.yaml
- .github/workflows/presubmit.yaml
- .github/workflows/validate-merge-queue.yaml
- .github/workflows/validate-pull-request.yaml
Enhancement
#705 
- This change allows for different validation on PR versus merge queue to workaround required status check restrictions. This will allow E2E test results to be reported correctly.
N/A
N/A
No.
No.
No.
> Enable separate validation on PR vs Push

- .github/workflows/validate-pull-request-presubmit.yaml
Enhancement
N/A
- This change corrects an issue where the validate workflow could not correctly differentiate running on versus merge queues
N/A
N/A
No.
No.
No.
> Remove strategy from validate workflow

- Dockerfile
- go.mod
- go.sum
Bug
N/A
This corrects the issue below, from [here](https://github.com/aws/aws-application-networking-k8s/security/code-scanning/tools/CodeQL/status/configurations/automatic/5820253ebecd708ce71ac44ab761d599f372d935050ad7f697897a4ef8e3a8e7):
> As of Go 1.21, toolchain versions must use the 1.N.P syntax.
>
> 1.23 in go.mod does not match this syntax and there is no additional toolchain directive, which may cause some go commands to fail.
N/A
Ran `make e2e-test` successfully.
N/A
**Will this PR introduce any new …
> Correct Go toolchain version

- docs/concepts/overview.md
documentation
Connected to, but not fixing, issue 535.
If any kubernetes users discover this project (which seems to be "an implementation of the Kubernetes Gateway API"), it could be really helpful to discuss the topic from issue 535.   Gateway API is meant to be v2 of Ingress API, which is usually applied to north/south traffic.  It takes time to understand that VPC Lattice is something else.
(Open to editing/wording changes).
> Docs: mention north/south traffic

- .github/workflows/validate-merge-queue-e2e-test.yaml
Bug
N/A
This upgrades the cache based on [recent decommissioning](https://github.blog/changelog/2025-03-20-notification-of-upcoming-breaking-changes-in-github-actions/#decommissioned-cache-service-brownouts).
N/A
N/A
No
No
No
> Upgrade GitHub Actions Cache

- test/suites/integration/access_log_policy_test.go
- test/suites/integration/httproute_header_match_test.go
- test/suites/integration/httproute_method_match_test.go
- test/suites/integration/httproute_path_match_test.go
- test/suites/integration/https_listener_weighted_rule_with_service_export_import_test.go
Bug
N/A
This corrects current E2E test failures to provide a clean baseline for upcoming changes. It also temporarily skips access log integration tests until these can be stabilized and reintroduced. #733 was created to track adding these tests back.
N/A
Ran E2E tests against my local cluster.
No
No
No
No
**Do all …
> Correct failing E2E tests

- docs/guides/deploy.md
N/A
This pull request includes several updates to the deployment guide for the AWS Gateway API Controller. The changes focus on improving clarity, fixing formatting issues, and ensuring consistency in the documentation.
Documentation improvements:
* [`docs/guides/deploy.md`](diffhunk://#diff-2af112c8fb0e40b2bcfb1cc932c4b7f7f6adf82333f01b26dd92475c6c8ac0edL5-R21): Improved sentence structure and clarity in the introductory section and various instructions. [[1]](diffhunk://#diff-2af112c8fb0e40b2bcfb1cc932c4b7f7f6adf82333f01b26dd92475c6c8ac0edL5-R21) [[2]](diffhunk://#diff-2af112c8fb0e40b2bcfb1cc932c4b7f7f6adf82333f01b26dd92475c6c8ac0edR33-R68)
* [`docs/guides/deploy.md`](diffhunk://#diff-2af112c8fb0e40b2bcfb1cc9 …
> fix formatting issues in deploy.md

- docs/guides/advanced-configurations.md
- pkg/gateway/model_build_rule.go
- pkg/gateway/model_build_rule_test.go
- pkg/utils/priority_queue.go
- test/suites/integration/httproute_rule_priority_test.go
Feature
#719 
This adds support for a custom annotation on HTTPRoutes to manually assign a priority for a rule. You can manually assign priorities to rules using the custom annotation `application-networking.k8s.aws/rule-{index}-priority`. 
`test/suites/integration/httproute_rule_priority_test.go` was added to confirm manually assigned priorities are reflected on VPC Lattice resources correctly.
No.
No, this change is backwards compatible with existing routes.
**Does this PR introduce …
> Add Support for Priority Configuration in HTTPRoute Resource

- .github/workflows/publish-doc.yaml
Potential fix for [https://github.com/aws/aws-application-networking-k8s/security/code-scanning/1](https://github.com/aws/aws-application-networking-k8s/security/code-scanning/1)
To fix the issue, we will add a `permissions` block at the workflow level to explicitly define the required permissions. Based on the workflow's operations, it likely needs `contents: write` to deploy documentation using `mike`. However, we will start with the minimal permissions (`contents: read`) and adjust to `contents: write` if necessary for the workflow to function correctly.
The `permissions` block will be added at the root level of the workflow, applying to all jobs. This ensures that the `GITHUB_TOKEN` used in the workflow has only the necessary permissions.
---
_Suggested fixes powered by Copilot …
> Potential fix for code scanning alert no. 1: Workflow does not contain permissions

- .github/dependabot.yml
Fix for Dependabot configuration 
Cleanup
It fix the Dependabox configuration since there was a problem with the Dependency graphs 
I tested it in my own fork and now is working as expected
NA
No
No
No
```release-note
```
**Do all end-to-end tests successfully pass when running `make e2e-test`?**:
```
NA
```
By submitting …
> Fix for Dependabot configuration 

- docs/faq.md
Documentation
N/A
This adds details on how to prevent 503 errors during deployments.
N/A
N/A
N/A
No.
No.
```release-note
Update FAQ with: "How do I prevent 503 errors during deployments?"
```
> Update FAQ with: "How do I prevent 503 errors during deployments?"

- .github/workflows/dependabot-make-presubmit.yml
Small PR to address [these failures](https://github.com/aws/aws-application-networking-k8s/actions/runs/17906247757/job/50907838993?pr=821) when dependabot attempts to run:
```
...
mocks/controller-runtime/client/generate.go:3: running "mockgen": exec: "mockgen": executable file not found in $PATH
pkg/aws/cloud.go:24: running "mockgen": exec: "mockgen": executable file not found in $PATH
pkg/aws/services/tagging.go:15: running "mockgen": exec: "mockgen": executable file not found in $PATH
pkg/deploy/externaldns/dnsendpoint_manager.go:20: running "mockgen": exec: "mockgen": executable file not found in $PATH
pkg/deploy/lattice/access_log_subscription_manager.go:16: running "mockgen": exec: "mockgen": executable file not found in $PATH
pkg/gateway/model_build_lattice_service.go:21: running …
```
> Update dependabot to install dependencies

- pkg/controllers/accesslogpolicy_controller.go
- pkg/controllers/gateway_controller.go
- pkg/controllers/route_controller.go
- pkg/controllers/serviceexport_controller.go
- pkg/deploy/lattice/error.go
- pkg/deploy/lattice/service_manager.go
- pkg/deploy/lattice/service_manager_test.go
- pkg/deploy/lattice/service_network_manager.go
- pkg/deploy/lattice/service_network_manager_test.go
- pkg/deploy/lattice/target_group_manager.go
- pkg/deploy/lattice/target_group_manager_test.go
- pkg/deploy/lattice/target_group_synthesizer.go
- pkg/deploy/lattice/targets_synthesizer.go
- pkg/deploy/lattice/targets_synthesizer_test.go
- pkg/runtime/errors.go
- pkg/runtime/reconcile.go
- pkg/runtime/reconcile_test.go
Cleanup and Fix
Fix `HandleReconcileError` function to enable exponential backoff.
Incase of transient errors from lattice apis keep static 10 seconds delay. 
> [Exponential backoff](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/util/workqueue/default_rate_limiters.go#L116) is problematic here because for operations like target group deletion where target draining takes time, this results in unnecessarily long delays in reconciliation. 
According to the [docs](https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.22.1/pkg/reconcile)
```
If the returned error is non-nil:
the Result is ignored and the request will requeued using exponential backoff …
```
> Exponential backoff for reconciler requests
