aws/aws-application-networking-k8s

- helm/Chart.yaml
- helm/values.yaml
Upgrade
N/A
N/A
N/A
Manual e2e integration testing is done.
No.
No.
No.
No.
```release-note
```
> release artifacts for release v0.0.9

- examples/deploy-v0.0.9.yaml
Upgrade deploy yaml file
N/A
Upgrade
N/A
Yes.
N/A
No
No
No
```release-note
```
> Add deploy-v0.0.9.yaml

- controllers/gatewayclass_controller.go
> Fix gatewayclass conformance test gap

- docs/developer.md
**Which issue does this PR fix**:  documentation
**What does this PR do / Why do we need it**: add e2e test doc
```release-note
```
> Update developer.md, adding some e2e test doc

- docs/deploy.md
- examples/deploy-v0.0.10.yaml
- helm/Chart.yaml
- helm/values.yaml
> Release v0.0.10

- controllers/gateway_controller.go
- controllers/httproute_controller.go
- pkg/gateway/model_build_servicenetwork.go
- pkg/gateway/model_build_targetgroup.go
#8 
* Once gateway object is accepted by controller, the controller will update the "Accepted" condition of this gateway object.
* Controller also update the listener status of this gateway object
Manually verify them through gateway API conformance tests
* GatewayObservedGenerationBump
* GatewayInvalidRouteKind
run e2e test OK
**Does this PR introduce any user-facing …
> Update Gateway Object Condition Status and Listener Status

- helm/Chart.yaml
- helm/values.yaml
Release
v0.0.11
```release-note
```
> release artifacts for release v0.0.11

- docs/deploy.md
- examples/deploy-v0.0.11.yaml
cleanup/documentation
Renew documentation, add new example (v0.0.11), and clear old example (v0.0.7).
```release-note
```
> Update deploy docs and add v0.0.11 example

- docs/enviroment.md
documentation
document configuration variables to run AWS gateway API controller
```release-note
```
> Add docs on the configuration variables for gateway API

- helm/Chart.yaml
- helm/values.yaml
> release artifacts for release v0.0.12

- docs/deploy.md
- examples/deploy-v0.0.12.yaml
> Update deploy docs and add v0.0.12 example

- docs/getstarted.md
**What type of PR is this?** documentation
**Which issue does this PR fix**: It's not a fix, but improvement
**What does this PR do / Why do we need it**: The previous documentation commands, steps can be optimized.
**If an issue # is not available please add repro steps and logs from aws-gateway-controller showing the issue**: N/A
**Testing done on this change**: Documentation - we run spellcheck
**Automation added to e2e**: N/A
**Will this PR introduce any new dependencies?**: N/A
**Will this break upgrades or downgrades. Has updating a running cluster been tested?**: N/A
**Does this PR introduce any user-facing change?**: N/A
```release-note
the updated Getting Started guide offers some user steps optimization.
```
By submitting this pull request, I confirm that my contribution is made …
> Simplified getting started commands

- controllers/httproute_controller.go
cleanup
299
removes outdated comments
none
none
none
no
no
> 299: removed outdated comments

- docs/deploy.md
- examples/deploy-v0.0.15.yaml
- helm/Chart.yaml
- helm/values.yaml
What type of PR is this?
release v0.0.15
> Release artifacts for v0.0.15

- Dockerfile
- Makefile
- cmd/aws-application-networking-k8s/main.go
Note:
Move gateway-api main.go into go idiomatic cmd directory.
Tests:
1. make run
2. build image with docker 
1. docker build .
2. docker run <new_image_id>
> move controller's main into cmd

- test/go.mod
- test/go.sum
fix for missing aws-sdk in tests module after removing sdk override
> add aws-sdk-go to tests

- helm/templates/configmap.yaml
> fix: quote accountid in configmap

- docs/developer.md
Update developers doc with required tools and cluster setup
> update developer.md  with required tools and cluster setup

- config/manager/kustomization.yaml
- config/rbac/cluster-role-controller.yaml
- helm/crds/k8s-gateway-v0.6.1.yaml
- helm/templates/cluster-role-controller.yaml
Feature
Part of #25 
This adds permission to interact with GRPCRoute resources and adds the CRD for GRPCRoute in Helm. The diff is large because `/config/crds/bases/k8s-gateway-v0.6.1.yaml` is copied directly over to `/helm/crds/k8s-gateway-v0.6.1.yaml` and there were some indentation differences between them. This should not affect functionality, per discussion with @solmonk 
N/A
N/A
No
**Will this break upgrades or downgrades. Has updating a running cluster …
> Added GRPCRoute permissions and Helm CRD configuration

- docs/grpc.md
- docs/reference/grpc-route.md
Documentation
#25 
Adds documentation for GRPCRoute. Shows users how to deploy an example gRPC-based server and route traffic to it. Also shows the specific features available and limitations surrounding GRPCRoute.
N/A
N/A
No
No
Documentation only.
```release-note
```
By submitting this pull request, I confirm that my …
> Added GRPCRoute docs

- config/rbac/cluster-role-controller.yaml
- helm/templates/cluster-role-controller.yaml
- pkg/gateway/model_build_targetgroup.go
> Add missing permissions

- docs/deploy.md
- examples/deploy-v0.0.16.yaml
- helm/Chart.yaml
- helm/values.yaml
**Which issue does this PR fix**: Release artifacts for v0.0.16
**What does this PR do / Why do we need it**: Release artifacts for v0.0.16
```release-note
```
> Release artifacts for v0.0.16

- docs/reference/target-group-policy.md
- examples/grpcbin-route.yaml
- examples/grpcbin-server.yaml
- examples/grpcurl-runner-pod.yaml
- examples/target-group-policy.yaml
- Add more grpc yaml examples
-  Shows more fields in TragetGroupPolicy example
```release-note
```
> Add more grpc yaml examples

- examples/recommended-inline-policy.json
documentation
**Which issue does this PR fix**: #48 
**What does this PR do / Why do we need it**: This PR scopes down the recommended inline policy according to the [public documentation](https://docs.aws.amazon.com/aws-managed-policy/latest/reference/VPCLatticeFullAccess.html)
**Testing done on this change**: N/A
**Automation added to e2e**: No
**Will this break upgrades or downgrades. Has updating a running cluster been tested?**:  N/A
**Does this PR introduce any user-facing change?**: No
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …
> docs: scope down recommended inline policy (#48)

- docs/deploy.md
- examples/deploy-v0.0.17.yaml
- helm/Chart.yaml
- helm/values.yaml
> release artifacts for release v0.0.17

- controllers/iamauthpolicy_controller.go
Note:
Add IAMAuthPolicy watchers for Gateway and Routes.
Tested manually with creation and deletion of Gateway, Route, and IAMAuthPolicy in different order.
If GW or Route does not exists IAMAuthPolicy status will be TargetNotFound. Once GW or Route is created, policy will eventually be there, after few rounds of reconciliation.
Listening GW events is easy, and does not trigger redundant reconciles for Auth policy. But Route updates are massive, we need to revisit Route logic and how we update K8s Status or Spec, otherwise our watchers generate 4-5 times extra load for each route update.
I tried to use GenerationChangedPredicate for Route events, but it didnt work for me. Route mostly update K8s Status, which is filtered out by GenerationChangedPredicate. I dont know why/how it works for …
> add IAMAuthPolicy watchers for Gateway and Routes

- helm/templates/cluster-role-controller.yaml
Note:
Update iam auth policy helm template rbac for status
> update helm template with iamauthpolicy status

- pkg/utils/common_test.go
> Change Chunks() unit test

- test/suites/integration/defined_target_ports_test.go
- test/suites/integration/vpc_association_policy_test.go
> Fix e2e test flakiness

- controllers/iamauthpolicy_controller.go
- test/pkg/test/framework.go
- test/pkg/test/httpapp.go
- test/pkg/test/nginxapp.go
- test/suites/integration/iamauthpolicy_test.go
Note:
- Add e2e tests for IAM Auth Policy
- Update test framework logging and add parallel processing for k8s objects create/update/delete
There seem to be regression in full test suite, not related to IAM Auth. Notable one is Health Check Config.
Test results:
```sh
IAM Auth Policy GroupName Error
/Users/mhlbrz/workplace/aws-application-networking-k8s/test/suites/integration/iamauthpolicy_test.go:93
2023-11-08T14:40:12.991-0800	INFO	test/framework.go:223	Creating objects: *v1.Deployment/tiger-1-454p2dec4o, *v1.Service/http-app, *v1beta1.HTTPRoute/http-app
• [1.140 seconds]
IAM Auth Policy Kind Error
/Users/mhlbrz/workplace/aws-application-networking-k8s/test/suites/integration/iamauthpolicy_test.go:99
• [1.102 seconds] …
```
> Add IAM Auth Policy e2e tests

- Makefile
> Fix Makefile git tag command

- mkdocs.yml
> Add reference/iam-auth-policy.md link in the mkdocs.yml

- docgen/.gitignore
- docgen/README.md
- docgen/api-reference-base.md
- docgen/config.json
- docgen/template/members.tpl
- docgen/template/pkg.tpl
- docgen/template/placeholder.go
- docgen/template/type.tpl
Note:
Add CRD doc generator. Follow README for instructions.
> Add CRD doc generator

- docs/concepts/custom-domain-name.md
- docs/concepts/https.md
- docs/concepts/overview.md
- docs/faq.md
- docs/guides/deploy.md
- docs/guides/getstarted.md
- docs/guides/multi-sn.md
documentation
* Fixes #468 and #435 
* Add explanation on default service network
* Fix broken image links
* and minor nitpicks
```release-note
```
> Update deployment instructions

- docs/api-types/gateway.md
- docs/api-types/grpc-route.md
- docs/api-types/http-route.md
- docs/api-types/iam-auth-policy.md
- docs/api-types/service.md
- docs/api-types/target-group-policy.md
- docs/api-types/vpc-association-policy.md
- docs/concepts/grpc.md
- docs/faq.md
- mkdocs.yml
documentation
`mkdocs serve` (we should do this by default btw)
```release-note
```
> Update Gateway docs and fix styles

- README.md
- mkdocs.yml
documentation
Correct links to the new doc pages
> Doc: Update Readme Links

- config/crds/bases/application-networking.k8s.aws_targetgrouppolicies.yaml
- helm/crds/application-networking.k8s.aws_targetgrouppolicies.yaml
update auto generated CRD's documentation
> fix crd autogen

- config/iam/recommended-inline-policy.json
- docs/guides/deploy.md
- examples/recommended-inline-policy.json
> Add missing iam policies for tags in documentation

- README.md
- config/manager/kustomization.yaml
- docs/guides/deploy.md
- examples/deploy-v1.0.0.yaml
- helm/Chart.yaml
- helm/values.yaml
> Release v1.0.0

- config/rbac/cluster-role-controller.yaml
- helm/templates/cluster-role-controller.yaml
bug fix: missing update rbac for targetgrouppolicies and vpcassociationpolicies status update
#531
> update rbac for targetgrouppolicies and vpcassociationpolicies

- README.md
- config/manager/kustomization.yaml
- docs/guides/deploy.md
- examples/deploy-v1.0.1.yaml
- helm/Chart.yaml
- helm/values.yaml
> Release artifacts for v1.0.1

- docs/guides/deploy.md
- helm/values.yaml
> Update debug mode docs

- docs/guides/deploy.md
- examples/recommended-inline-policy.json
- Make [recommended-inline-policy.json](https://github.com/aws/aws-application-networking-k8s/blob/ef058d04d7e914bd8ea2d0f715c32daf37b2be68/examples/recommended-inline-policy.json#L1) content and the one shown in the deploy.md in sync
- some doc bug and typo fixes 
> Make recommended-inline-policy.json content and the one shown in the deploy.md in sync

- README.md
- config/manager/kustomization.yaml
- docs/guides/deploy.md
- examples/deploy-v1.0.2.yaml
- helm/Chart.yaml
- helm/values.yaml
> Release artifacts for v1.0.2

- Makefile
- config/iam/recommended-inline-policy.json
- docs/guides/deploy.md
- examples/recommended-inline-policy.json
- test/suites/integration/iamauthpolicy_test.go
- Add more controller permissions in recommended-inline-policy.json
- Fix e2e test code compiling error
New permissions could run access_log_policy_test.go success
> Add more controller permissions in recommended-inline-policy.json

- pkg/aws/services/vpclattice.go
bugfix
#586 
A small change that prevents NPE on error
```release-note
```
> Fix permission denied error handling for SN tags

- README.md
- config/manager/kustomization.yaml
- docs/guides/deploy.md
- examples/deploy-v1.0.3.yaml
- helm/Chart.yaml
- helm/values.yaml
> Release artifacts for v1.0.3

- .github/workflows/e2e-test.yaml
- .github/workflows/presubmit.yaml
- Dockerfile
- scripts/release-controller.sh
feature
#579 - should be able to support ARM64 next release.
Fixed dockerfile to support multiarch and optimized build to utilize cache
Tested using personal fork
```release-note
```
> Optimize docker build and support multi-arch (ARM64)

- Makefile
bug
https://github.com/aws/aws-application-networking-k8s/issues/596
The current Makefile commands for generating the webhook cert aren't quite right. It was working before I added the ```rm``` line because the files already existed. This fixes failures when running ```build-deploy```.
Ran ```make build-deploy``` in "clean" directories, confirmed correct patching.
n/a
n/a
n/a
no
By submitting this pull request, I confirm that my …
> Fix for Makefile webhook secrets

- README.md
- config/manager/kustomization.yaml
- docs/guides/deploy.md
- examples/deploy-v1.0.4.yaml
- helm/Chart.yaml
- helm/values.yaml
> Release artifacts for v1.0.4

- cmd/aws-application-networking-k8s/main.go
- go.mod
- pkg/aws/cloud.go
- pkg/aws/metrics/collector.go
- pkg/aws/metrics/collector_test.go
- pkg/aws/metrics/instruments.go
feature
#601 
It provides metrics on all lattice API calls, return code and error msgs.
```
curl -s localhost:8080/metrics | grep aws_api_requests_total
aws_api_requests_total{error_code="",operation="CreateListener",service="VPC Lattice",status_code="201"} 1
aws_api_requests_total{error_code="",operation="CreateRule",service="VPC Lattice",status_code="201"} 1
aws_api_requests_total{error_code="",operation="CreateService",service="VPC Lattice",status_code="201"} 1
aws_api_requests_total{error_code="",operation="CreateServiceNetworkServiceAssociation",service="VPC Lattice",status_code="200"} 1
aws_api_requests_total{error_code="",operation="CreateTargetGroup",service="VPC …
```
> Adding more Metrics

- README.md
- config/manager/kustomization.yaml
- docs/guides/deploy.md
- files/controller-installation/deploy-v1.0.5.yaml
- helm/Chart.yaml
- helm/values.yaml
Release artifacts for release v1.0.5
> Release artifacts for release v1.0.5

- docs/guides/getstarted.md
- scripts/github-release.sh
Change github-release.sh to substitute new version number in the getstarted.md
> Change github-release.sh to substitute new version number in the getstarted.md

- api-reference/index.html
- api-types/access-log-policy/index.html
- api-types/gateway/index.html
- api-types/grpc-route/index.html
- api-types/http-route/index.html
- api-types/iam-auth-policy/index.html
- api-types/service-export/index.html
- api-types/service-import/index.html
- api-types/service/index.html
- api-types/target-group-policy/index.html
- api-types/vpc-association-policy/index.html
- concepts/concepts/index.html
- concepts/index.html
- concepts/overview/index.html
- conformance-test/index.html
- contributing/developer-cheat-sheet/index.html
- contributing/developer/index.html
- faq/index.html
- guides/advanced-configurations/index.html
- guides/custom-domain-name/index.html
- guides/deploy/index.html
- guides/environment/index.html
- guides/grpc/index.html
- guides/https/index.html
- guides/pod-readiness-gates/index.html
- guides/ram-sharing/index.html
> Add old urls redirect pages

- mkdocs.yml
Add tls-route.md in the mkdocs.yml
> Add tls-route.md in the mkdocs.yml

- README.md
- config/manager/kustomization.yaml
- docs/guides/deploy.md
- files/controller-installation/deploy-v1.0.7.yaml
- helm/Chart.yaml
- helm/values.yaml
> Release artifacts for v1.0.7

- mkdocs.yml
documentation
This PR removes the dependency on third-party content providers for static files and replaces it with a domain hosted completely on AWS infrastructure, enhancing overall security. Through AWS Amplify, this content will now be served to the AWS CDN with Cloudfront.
This change is necessary to comply with internal AWS security requirements.
Doc change
Doc change
No
**Will this break upgrades or downgrades. Has updating a running cluster been …
> Use AWS-based infrastructure to host static files

- scripts/setup.sh
Bug
N/A
This further improves error handling when running `make setup`.
Ran `make setup` successfully again.
N/A
No.
No.
N/A
> Improve Setup Error Handling

- helm/Chart.yaml
- helm/values.yaml
Cleanup
N/A
This corrects the Helm version that was not incremented in the last release.
N/A
N/A
N/A
No.
No.
> Increment Helm version

- README.md
- config/manager/kustomization.yaml
- docs/guides/deploy.md
- docs/guides/getstarted.md
- files/controller-installation/deploy-v1.1.5.yaml
- helm/Chart.yaml
- helm/values.yaml
- scripts/setup.sh
* Support Standalone Service Creation & Surface Service ARN by @rlymbur in [#818](https://github.com/aws/aws-application-networking-k8s/pull/818)
* Exponential backoff for reconciler requests by @vbedi in [#822](https://github.com/aws/aws-application-networking-k8s/pull/822)
**Full Change log**: https://github.com/aws/aws-application-networking-k8s/compare/v1.1.4...v1.1.5
> Release artifacts for release v1.1.5
